---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(janitor)
library(fastDummies)
library(GGally)
library(ggfortify)
library(mosaic)
library(mosaicData)
```

```{r}
library(readr)
kc_house_data <- read_csv("data/kc_house_data.csv")
View(kc_house_data)
```

##Q1 Tidy the data for regression


```{r}
kc_house_data%>%
  clean_names()
```

```{r}
glimpse(kc_house_data)
```


```{r}
houses_tidy <- kc_house_data %>%
  select(-c("id", "date", "sqft_living15", "sqft_lot15", "zipcode")) %>%
  mutate(waterfront = as.logical(waterfront)) %>%
  mutate(renovated = yr_renovated != 0) %>%
  select(-"yr_renovated") %>%
  mutate(view = as_factor(view)) %>% 
  mutate(condition = as_factor(condition)) %>%
  mutate(grade = as_factor(grade))
```





```{r}
head(houses_tidy)
```
```{r}
kchouseclean <- kc_house_data %>%
  drop_na()
```


```{r}
alias(price ~ ., data = houses_tidy)
```

#look for the -1 numerical


```{r}
houses_tidy <- houses_tidy %>%
  select(-"sqft_living")
```


```{r}
houses_tidy_numeric <- houses_tidy %>%
  select_if(is.numeric)

houses_tidy_nonnumeric <- houses_tidy %>%
  select_if(function(x) !is.numeric(x))

houses_tidy_nonnumeric$price <- houses_tidy$price
```

```{r}
ggpairs(houses_tidy_numeric)
```




```{r}
ggpairs(houses_tidy_numeric, columns = c(1, 2, 3, 4))
```


###This is all incorrect and now following the homewor.

##reduced the amount of data to only 5 variables.

```{r}
kcsimplehousedata <-kchouseclean%>%
  select(price,yr_built,yr_renovated,bedrooms,grade)
```


##First Predictor

```{r}
kcsimplehousedata%>%
  ggplot(aes(x = price, y = yr_built))+
  geom_point()+
  theme_classic()+
  geom_smooth(method = "lm", se = FALSE)
```


```{r}
skimr::skim(kcsimplehousedata)%>%
  view()
```

```{r}
kcsimplehousedata%>%
  ggpairs(aes(colour = price, alpha = 0.5))
```







